server:
  port: 8081
spring:
  application:
    name: song-service
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song-db}"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    # hibernate:
      # ddl-auto: update
    show-sql: true
    properties:
      hibernate:
resource-service:
  url: "${RESOURCE_SERVICE_URL:http://localhost:8080}"